---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-placement
  namespace: guestbook-upstream
spec:
  clusterSelector:
    matchLabels:
      purpose: development