---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: guestbook-app-latest
  namespace: guestbook-app
spec:
  type: GitHub
  pathname: https://github.com/xphyr/examples.git