---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd-app
  namespace: httpd-app
  labels:
    app: httpd-app
  annotations:
    apps.open-cluster-management.io/github-path: httpd-ex
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: httpd-app/httpd-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: httpd-placement
